### ISSUE TITLE
RTC Date on big_osd

### ISSUE THREAD

**Issue by rampa069** [mist-devel/mist-firmware#110]
Is there any parameter to disable the RTC datetime on top of OSD? as i dont have rtc, it keeps swinging... :-)

**Comment by gyurco** [comment]
Not yet, I assumed everybody has an RTC :)

**Comment by rampa069** [comment]
you are right.. anybody needs a RTC.. :-)  (where can i find one?)

**Comment by gyurco** [comment]
I have no idea, I built it for myself :)
Meanwhile I can replace it with some generic header if the RTC is not found - just thinking about what would be good there.

**Comment by rampa069** [comment]
core name and version?

**Comment by gyurco** [comment]
Just added it (and some more changes trying to prevent bricking during update).

**Comment by rampa069** [comment]
tried it and works! thank you very much.
