### ISSUE TITLE
Core developer's guide to the firmware

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-firmware#26]
Is there a README or something I can use to know the features of the firmware? For instance, I would like to know how to interact with the OSD options. I only know to add T and 1-bit O options. But I know that other cores do more functions, like loading a file. Would it be possible to have an O options for many bits (2, 3...)?

**Comment by gyurco** [comment]
Probably you already figured it out...
But for reference:
Tx - Toggle
Ox(y) Option, can be more bits, readable with status[y:x] from user_io
F - file transfer
D - file mount
V - version
