### ISSUE TITLE
Don't know who develops to send bug reports...

### ISSUE THREAD

**Issue by Televicious** [mist-devel/mist-firmware#3]
Can see diffenet development all over, but I'll just post a main bug repot here. This is using all the latest cores and firmware as of this post date.

FPGA64 - Screen is almost black seems off center. Loading freezes when using a d64 image.

Gameboy - Picture is half off screen on the left. Audio is a bit plain sounding.

SMS - NTSC mode the screen turns red and timing is all over the place as well as the audio is pitch shifted. Lots of slowdowns in NTSC and PAL modes.

Minimig - Not sure if this is how it is on Amiga, but while playing title track on lotus 3 there are skips when loading screens.

Still checking on the rest, but I'll update periodically. 

Great work. Very amazing device. Learning and building things with it all the time.

**Comment by Newsdee** [comment]
Hi, this repo is for firmware changes... can I suggest posting this on the mist-binaries repo instead?
