### ISSUE TITLE
How to know the size of mounted image (S option)?

### ISSUE THREAD

**Issue by sorgelig** [mist-devel/mist-firmware#4]
If i use S option in OSD, core gets event about mounting - this is good. But i cannot see how i can get the size of mounted image. How to get it? Cannot find it in firmware sources.

**Comment by harbaum** [comment]
Hi,

there's currently no way to tell how big a mounted image is. So far it was 
always possible to read this from inside the image. E.g. if the image was a 
file system the core would read the partition table and the boot sectors.

Regards,
  Till

Am Mittwoch, Juni 08, 2016, 23:23:39 schrieb sorgelig:
> If i use S option in OSD, core gets event about mounting - this is good. But
> i cannot see how i can get the size of mounted image. How to get it? Cannot
> find it in firmware sources.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mist-devel/mist-firmware/issues/4

-- 
--
Dr. Till Harbaum <Till@Harbaum.org>

**Comment by sorgelig** [comment]
Ok. In the core I'm working on, there is no way to know the image size in advance, but i have to scan the whole image before use. I've added new command definition into FW sending the size of image.
I will test it, and if it will go smooth without affecting older cores, then i will push the commit.

**Comment by harbaum** [comment]
Sounds good and will be useful for e.g. the PlusToo core which may use this when formatting hdd images.

**Comment by sorgelig** [comment]
I've pushed commits and tested on SAM Coupe core. Works without problems.
See https://github.com/sorgelig/SAMCoupe_MIST/blob/master/mist_io.v for handling 'h1d command.
