### ISSUE TITLE
core.arc doesn't work anymore

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-firmware#73]
In one of the recent firmware updates, `core.arc` as the boot core has stopped working. This fails at least on _firmware_210618_ .

**Comment by jotego** [comment]
Thank you for solving this. Could you upload a binary, please?

**Comment by gyurco** [comment]
Jose, here's one. There's still a strangeness, when you're uploading via USB-Blaster, the CORE.ARC file is loaded, and the wrong ROM is opened. But it won't affect normal use.
[fw-210725.zip](https://github.com/mist-devel/mist-firmware/files/6873845/fw-210725.zip)

**Comment by jotego** [comment]
Thank you so much. I installed it right away. I think the problem of not loading the ROM when uploading via USB-Blaster was present before. If you ever have time to fix it, it'd make my developer life a little better :-)

**Comment by gyurco** [comment]
(Hopefully) fixed in today's release.
