### ISSUE TITLE
MOD byte is not sent with core.arc

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-firmware#77]
There is a difference in how the .arc file is read. When it is done at boot, by means of the core.arc, the MOD byte is not sent. When the same core.arc is read again via the OSD menu, the MOD byte is read. 

I can tell because my vertical cores depend on the MOD byte to flip the OSD. The OSD is only rotated when the ARC was manually loaded from the OSD menu.

I think there could be a bug related to this in the firmware.

**Comment by gyurco** [comment]
It's fixed in the latest release.

**Comment by jotego** [comment]
Thank you!
