### ISSUE TITLE
Core version hidden by firmware in OSD

### ISSUE THREAD

**Issue by jotego** [mist-devel/mist-firmware#88]
In firmware **220220**, the OSD only shows the name of the .arc file but it doesn't show the contents of the **V** line in the config string. This line is important because it lets the user identify which version of the core they are running. That helps debugging the cores. 

Could you restore the old behaviour and show the core version in the OSD?

Thank you

**Comment by gyurco** [comment]
I thought it was already fixed:
https://github.com/mist-devel/mist-firmware/issues/86
I'll recheck.

**Comment by gyurco** [comment]
Just loaded Golden Axe (great S16 finally released!), it displays "GOLDNAXE df574c6 - patreon.c". Is there any special you do to trigger the bug?

**Comment by jotego** [comment]
I think this has been fixed for a while now.
